services:
  - type: web
    name: monitor-emergencia-colombia
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --preload --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: AUTO_UPDATE
        value: "true"
      - key: REQUEST_TIMEOUT
        value: "35"
